version: '3'

services:
  kvdnode0:
    container_name: kvdnode0
    image: "kava/kavanode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  kvdnode1:
    container_name: kvdnode1
    image: "kava/kavanode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  kvdnode2:
    container_name: kvdnode2
    image: "kava/kavanode"
    environment:
      - ID=2
      - LOG=${LOG:-kvd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  kvdnode3:
    container_name: kvdnode3
    image: "kava/kavanode"
    environment:
      - ID=3
      - LOG=${LOG:-kvd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
