[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version="=0.23.1"


# Copied from cosmos-sdk, constraints switched to overrides

[[override]]
  name = "github.com/bgentry/speakeasy"
  version = "~0.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[override]]
  name = "github.com/mattn/go-isatty"
  version = "~0.0.3"

[[override]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[override]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[override]]
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[override]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=0.10.1"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.9.2"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.22.8"

[[override]]
  name = "github.com/bartekn/go-bip39"
  branch = "master"

[[override]]
  name = "github.com/zondax/ledger-goclient"
  revision = "39ba4728c137c75718a21f9b4b3280fa31b9139b"

[prune]
  go-tests = true
  unused-packages = true
