apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-gaiad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-gaiacli
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

