apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-gaiad
  labels:
    app: kava
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-gaiacli
  labels:
    app: kava
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

