apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-kvd2
  labels:
    app: kava
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kava-pvc-kvcli2
  labels:
    app: kava
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

