name: Continuous Deployment (Internal Testnet)
# run after every successful CI job of new commits to the master branch
on:
  workflow_run:
    workflows: [Continuous Integration (Kava Master), Continuous Integration (Commit)]
    types:
      - completed
jobs:
  # run default ci checks against master branch
  no-op:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/ci-lint.yml
