name: Continuous Integration (Default Checks)

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true
      - name: build application
        run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true
      - name: run unit tests
        run: make test
      - name: run e2e tests
        run: make docker-build test-e2e
  validate-internal-testnet-genesis:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo from master
          uses: actions/checkout@v3
          with:
           ref: master
        - name: checkout version of kava used by internal testnet
          run: |
           git pull -p
           git checkout $(cat ./ci/env/kava-internal-testnet/KAVA.VERSION)
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: "1.19"
            check-latest: true
            cache: true
        - name: build kava cli
          run: make install
        - name: validate testnet genesis
          run: kava validate-genesis ci/env/kava-internal-testnet/genesis.json
  validate-protonet-genesis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true
      - name: build kava cli
        run: make install
      - name: validate protonet genesis
        run: kava validate-genesis ci/env/kava-protonet/genesis.json
