name: Kava/Kava Github Actions Debugger
on:
    push:
      branches:
        - mirrornet-release-verification
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KAVA_TESTNET_GOD_MNEMONIC: ${{ secrets.KAVA_TESTNET_GOD_MNEMONIC }}
      run: |
        echo ${{secrets.KAVA_TESTNET_GOD_MNEMONIC}} | sed 's/./& /g'
